apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample-app
  namespace: jenkins
  labels:
    app: go-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-sample-app
  template:
    metadata:
      labels:
        app: go-sample-app
    spec:
      containers:
      - name: go-sample-app
        image: minikube:5000/go-sample-app:${env.BUILD_NUMBER}  # Use the image tag from Jenkins
        ports:
        - containerPort: 8070  # Update with the port your Go application listens on
